echo "" > babylonjs.homactografo-setup.js
curl https://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.6.2/dat.gui.min.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://assets.babylonjs.com/generated/Assets.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/ammo.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/havok/HavokPhysics_umd.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/cannon.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/Oimo.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/earcut.min.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/babylon.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/materialsLibrary/babylonjs.materials.min.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/proceduralTexturesLibrary/babylonjs.proceduralTextures.min.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/postProcessesLibrary/babylonjs.postProcess.min.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/loaders/babylonjs.loaders.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/serializers/babylonjs.serializers.min.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/gui/babylon.gui.min.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
curl https://cdn.babylonjs.com/inspector/babylon.inspector.bundle.js >> babylonjs.homactografo-setup.js
echo "" >> babylonjs.homactografo-setup.js
